name: Publish

on:
  push:
    branches: [ actions ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set Up Stack
      uses: mstksg/setup-stack@v1
    - name: Build
      run: stack build && stack exec site build
